import React from "react";

const TermsPolicy = () => {
  return (
    <>
      <div className="rbt-main-content mb--0">
        <div className="rbt-daynamic-page-content center-width">
          <div className="rbt-dashboard-content rainbow-section-gap">
            <div className="banner-area">
              <div className="settings-area">
                <h3 className="title">Terms and Conditions of Use</h3>
              </div>
            </div>
            <div className="content-page">
              <div className="chat-box-list">
                <div className="content">
                  <h4>Last Updated: 11/19/2024</h4>
                  <p>
                    By using the services of MidyAI Design, you expressly agree
                    to comply with the terms and conditions outlined in this
                    document. These terms are designed to protect the interests
                    of MidyAI Design, its tools, legal representatives, and
                    users. If you do not agree to these terms, please refrain
                    from using our services.
                  </p>

                  <h4>1. Acceptance of Terms</h4>
                  <p>
                    Accessing and using the services provided by MidyAI Design
                    constitutes your full and unconditional agreement to these
                    terms. We reserve the right to modify these terms at any
                    time, and it is your responsibility to review them
                    periodically. Continued use of the service after any
                    modifications signifies your acceptance of the updated
                    terms.
                  </p>

                  <h4>2. Intellectual Property</h4>
                  <p>
                    All intellectual property rights related to MidyAI Design,
                    including but not limited to tools, software, designs,
                    trademarks, logos, generated content, and documentation, are
                    the exclusive property of MidyAI Design or its licensors.
                  </p>
                  <ul>
                    <li>
                      <strong>Usage Restrictions:</strong> You may not copy,
                      modify, distribute, sell, license, or exploit any
                      resources of MidyAI Design without prior written consent.
                    </li>
                    <li>
                      <strong>Generated Content:</strong> While you may use the
                      outputs generated by our tools for personal or commercial
                      purposes, MidyAI Design retains the rights to the
                      algorithms, processes, and systems that produce such
                      content.
                    </li>
                  </ul>

                  <h4>3. Limitation of Liability</h4>
                  <p>
                    MidyAI Design and its legal representatives shall not be
                    liable for:
                  </p>
                  <ul>
                    <li>
                      Direct, indirect, incidental, punitive, or consequential
                      damages arising from the use or inability to use our
                      tools.
                    </li>
                    <li>
                      Loss of data, revenue, or profits, even if advised of the
                      possibility of such damages.
                    </li>
                    <li>
                      Any inaccurate, inappropriate, or unlawful content
                      generated by users using our tools.
                    </li>
                  </ul>

                  <h4>4. User Accounts</h4>
                  <p>
                    To access certain features of MidyAI Design, you may need to
                    create an account. By doing so, you agree to:
                  </p>
                  <ul>
                    <li>
                      Provide truthful, complete, and up-to-date information.
                    </li>
                    <li>
                      Be responsible for the confidentiality of your login
                      credentials and all activities conducted under your
                      account.
                    </li>
                    <li>
                      Notify us immediately of any unauthorized use of your
                      account.
                    </li>
                  </ul>
                  <p>
                    We reserve the right to suspend or terminate accounts if we
                    suspect fraudulent, illegal, or otherwise inappropriate
                    activity.
                  </p>

                  <h4>5. Permitted Use</h4>
                  <p>By using MidyAI Design, you agree to:</p>
                  <ul>
                    <li>
                      Not use our tools to create content that infringes on the
                      rights of third parties, is illegal, defamatory, obscene,
                      discriminatory, or otherwise harmful.
                    </li>
                    <li>
                      Not attempt to decompile, reverse engineer, or extract the
                      source code of our tools or services.
                    </li>
                    <li>
                      Not use our services for competitive purposes or in ways
                      that could harm MidyAI Design’s reputation.
                    </li>
                  </ul>
                  <p>
                    Any unauthorized use will result in immediate termination of
                    access and potential legal action.
                  </p>

                  <h4>6. Indemnification</h4>
                  <p>
                    You agree to indemnify and hold harmless MidyAI Design, its
                    employees, affiliates, and legal representatives from any
                    claims, demands, losses, or damages, including reasonable
                    attorney fees, arising from:
                  </p>
                  <ul>
                    <li>
                      Your use of the tools and services provided by MidyAI
                      Design.
                    </li>
                    <li>Your violation of these terms and conditions.</li>
                    <li>
                      Any content you generate or actions you take using our
                      tools.
                    </li>
                  </ul>

                  <h4>7. Privacy and Data Protection</h4>
                  <p>
                    MidyAI Design collects and processes personal data in
                    accordance with its Privacy Policy. While we are committed
                    to protecting your information, we cannot guarantee absolute
                    security for data transmitted online.
                  </p>
                  <ul>
                    <li>
                      <strong>Consent:</strong> By using our services, you agree
                      to the collection and use of your data as outlined in our
                      policy.
                    </li>
                    <li>
                      <strong>User Responsibility:</strong> You are responsible
                      for safeguarding your credentials and personal data on
                      devices accessing the service.
                    </li>
                  </ul>

                  <h4>8. Dispute Resolution</h4>
                  <p>
                    In the event of a dispute, the parties agree to resolve any
                    conflict related to the use of MidyAI Design’s services
                    through amicable negotiation. If no agreement is reached,
                    the dispute will be submitted to binding arbitration under
                    the laws of the United States.
                  </p>
                  <ul>
                    <li>
                      <strong>Applicable Law:</strong> These terms are governed
                      by the laws of the United States, without regard to its
                      conflict of law principles.
                    </li>
                    <li>
                      <strong>Exclusive Jurisdiction:</strong> Any legal action
                      must be initiated in the courts located in the United
                      States.
                    </li>
                  </ul>

                  <h4>9. Termination of Service</h4>
                  <p>
                    MidyAI Design reserves the right to suspend or terminate
                    access to its services, accounts, or any part thereof at any
                    time, without notice, if it deems that these terms have been
                    violated or for any other necessary reason.
                  </p>

                  <h4>10. General Provisions</h4>
                  <ul>
                    <li>
                      <strong>Severability:</strong> If any provision of these
                      terms is deemed invalid or unenforceable, the remaining
                      provisions will remain in full force and effect.
                    </li>
                    <li>
                      <strong>Waiver:</strong> Failure to enforce any right or
                      provision of these terms by MidyAI Design shall not
                      constitute a waiver of such right or provision.
                    </li>
                  </ul>
                  <p>
                    Thank you for choosing MidyAI Design. Responsible use
                    ensures a safe and efficient experience for all our users.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TermsPolicy;
